/**
 * Generate a draw.io (diagrams.net) XML file representing a customised CAF
 * Azure Landing Zone for a specific customer.
 *
 * Output is plain XML (no compression) so it opens correctly in:
 *   - app.diagrams.net (web)
 *   - VS Code "Draw.io Integration" extension
 *   - desktop drawio.exe
 *
 * Design intent: replace the generic "Contoso" labels in the public CAF ALZ
 * reference architecture with the actual customer name, regions and workload
 * landing zones derived from the BOM / wave plan.
 */

function escapeXml(s) {
  return String(s == null ? "" : s)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}

// Sluggify for management-group naming (mg-{customer}-{tier}).
function slug(s) {
  return String(s || "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "")
    .slice(0, 32) || "customer";
}

// Cell-style strings (reused). Pulled out for readability.
const STYLES = {
  title:    "text;html=1;align=center;verticalAlign=middle;fontSize=20;fontStyle=1;fillColor=none;strokeColor=none;",
  subtitle: "text;html=1;align=center;verticalAlign=middle;fontSize=11;fontStyle=0;fillColor=none;strokeColor=none;fontColor=#555555;",
  sectionTitle: "text;html=1;align=left;verticalAlign=middle;fontSize=13;fontStyle=1;fillColor=none;strokeColor=none;fontColor=#0078D4;",
  mgBox:        "rounded=1;whiteSpace=wrap;html=1;fillColor=#DEEBF7;strokeColor=#2E75B6;fontSize=11;fontStyle=1;",
  mgBoxRoot:    "rounded=1;whiteSpace=wrap;html=1;fillColor=#0078D4;strokeColor=#003C66;fontColor=#FFFFFF;fontSize=12;fontStyle=1;",
  mgBoxPlatform:"rounded=1;whiteSpace=wrap;html=1;fillColor=#FFE699;strokeColor=#BF8F00;fontSize=11;fontStyle=1;",
  mgBoxLz:      "rounded=1;whiteSpace=wrap;html=1;fillColor=#C6EFCE;strokeColor=#1F7C45;fontSize=11;fontStyle=1;",
  hubBox:       "rounded=1;whiteSpace=wrap;html=1;fillColor=#0078D4;strokeColor=#003C66;fontColor=#FFFFFF;fontSize=12;fontStyle=1;",
  hubInner:     "rounded=1;whiteSpace=wrap;html=1;fillColor=#FFFFFF;strokeColor=#0078D4;fontSize=10;fontColor=#003C66;",
  spokeBox:     "rounded=1;whiteSpace=wrap;html=1;fillColor=#E2EFDA;strokeColor=#548235;fontSize=11;",
  drBox:        "rounded=1;whiteSpace=wrap;html=1;fillColor=#FFF2CC;strokeColor=#BF8F00;fontSize=11;fontStyle=1;",
  regionFrame:  "rounded=0;whiteSpace=wrap;html=1;fillColor=none;strokeColor=#999999;dashed=1;fontSize=12;fontStyle=2;fontColor=#666666;verticalAlign=top;align=left;",
  edge:         "endArrow=classic;html=1;rounded=0;strokeColor=#666666;",
  edgeDashed:   "endArrow=classic;html=1;rounded=0;strokeColor=#BF8F00;dashed=1;dashPattern=8 4;startArrow=classic;",
  edgeTree:     "endArrow=none;html=1;rounded=0;strokeColor=#666666;",
};

let _idCounter = 100;
function nextId() { return "n" + (_idCounter++); }

function cell(id, value, style, x, y, w, h, vertex = true, parent = "1") {
  return `<mxCell id="${id}" value="${escapeXml(value)}" style="${style}" vertex="${vertex ? 1 : 0}" parent="${parent}">` +
         `<mxGeometry x="${x}" y="${y}" width="${w}" height="${h}" as="geometry"/></mxCell>`;
}

function edge(id, source, target, style, label = "") {
  return `<mxCell id="${id}" value="${escapeXml(label)}" style="${style}" edge="1" parent="1" source="${source}" target="${target}">` +
         `<mxGeometry relative="1" as="geometry"/></mxCell>`;
}

/**
 * Build the full diagram.
 * @param {object} opts
 * @param {string} opts.customerName  Customer display name (used in title + MG names)
 * @param {string} opts.primaryRegion Display label for primary Azure region (e.g. "Southeast Asia")
 * @param {string} opts.drRegion      Display label for DR region (optional, empty hides DR section)
 * @param {string[]} opts.workloadGroups  Spoke landing zone names (e.g. ["Production","Non-Production","Identity","Management"])
 * @returns {string} draw.io XML (mxfile)
 */
function buildLandingZoneDiagram(opts) {
  _idCounter = 100;
  const customerName = (opts.customerName || "Customer").trim();
  const primaryRegion = (opts.primaryRegion || "Primary Region").trim();
  const drRegion = (opts.drRegion || "").trim();
  const customerSlug = slug(customerName);
  const workloadGroups = (opts.workloadGroups && opts.workloadGroups.length
    ? opts.workloadGroups
    : ["Production", "Non-Production"]
  ).slice(0, 8);

  const cells = [];

  // ===== TITLE =====
  cells.push(cell("title", `Azure Landing Zone \u2014 ${customerName}`, STYLES.title, 40, 20, 1520, 40));
  const subtitleText = `Primary Region: ${primaryRegion}` +
    (drRegion ? `   \u00B7   DR Region: ${drRegion}` : "") +
    `   \u00B7   Generated by Dr. BOM Agent`;
  cells.push(cell("subtitle", subtitleText, STYLES.subtitle, 40, 65, 1520, 25));

  // ===== LEFT: MANAGEMENT GROUP HIERARCHY =====
  cells.push(cell("mgSection", "Management Group Hierarchy", STYLES.sectionTitle, 40, 110, 460, 30));

  // Tree root: Tenant Root MG
  const tenantId = nextId();
  cells.push(cell(tenantId, "Tenant Root Group", STYLES.mgBoxRoot, 170, 150, 200, 40));

  // Customer-scoped intermediate MG
  const customerMgId = nextId();
  cells.push(cell(customerMgId, `mg-${customerSlug}`, STYLES.mgBoxRoot, 170, 210, 200, 40));
  cells.push(edge(nextId(), tenantId, customerMgId, STYLES.edgeTree));

  // Platform / Landing Zones / Sandbox / Decommissioned
  const platformId = nextId();
  cells.push(cell(platformId, "Platform", STYLES.mgBoxPlatform, 50, 290, 180, 36));
  const lzGroupId = nextId();
  cells.push(cell(lzGroupId, "Landing Zones", STYLES.mgBoxLz, 290, 290, 180, 36));
  const sandboxId = nextId();
  cells.push(cell(sandboxId, "Sandbox", STYLES.mgBox, 50, 540, 180, 36));
  const decomId = nextId();
  cells.push(cell(decomId, "Decommissioned", STYLES.mgBox, 290, 540, 180, 36));

  cells.push(edge(nextId(), customerMgId, platformId, STYLES.edgeTree));
  cells.push(edge(nextId(), customerMgId, lzGroupId, STYLES.edgeTree));
  cells.push(edge(nextId(), customerMgId, sandboxId, STYLES.edgeTree));
  cells.push(edge(nextId(), customerMgId, decomId, STYLES.edgeTree));

  // Platform children
  const connId = nextId();
  cells.push(cell(connId, "Connectivity", STYLES.mgBoxPlatform, 50, 360, 180, 30));
  const identId = nextId();
  cells.push(cell(identId, "Identity", STYLES.mgBoxPlatform, 50, 405, 180, 30));
  const mgmtId = nextId();
  cells.push(cell(mgmtId, "Management", STYLES.mgBoxPlatform, 50, 450, 180, 30));
  cells.push(edge(nextId(), platformId, connId, STYLES.edgeTree));
  cells.push(edge(nextId(), platformId, identId, STYLES.edgeTree));
  cells.push(edge(nextId(), platformId, mgmtId, STYLES.edgeTree));

  // Landing Zones children — derived from workloadGroups
  let lzChildY = 360;
  workloadGroups.forEach((wg) => {
    const wId = nextId();
    cells.push(cell(wId, `LZ \u2014 ${wg}`, STYLES.mgBoxLz, 290, lzChildY, 180, 30));
    cells.push(edge(nextId(), lzGroupId, wId, STYLES.edgeTree));
    lzChildY += 36;
  });

  // ===== RIGHT: HUB-SPOKE TOPOLOGY =====
  cells.push(cell("netSection", `Hub-Spoke Topology \u2014 ${primaryRegion}`, STYLES.sectionTitle, 560, 110, 1000, 30));

  // Region frame
  cells.push(cell(nextId(), `Primary Region: ${primaryRegion}`, STYLES.regionFrame, 560, 150, 1000, 540));

  // Hub VNet (centered)
  const hubX = 940, hubY = 250, hubW = 240, hubH = 160;
  const hubId = nextId();
  cells.push(cell(hubId, "Hub VNet", STYLES.hubBox, hubX, hubY, hubW, hubH));

  // Hub inner components
  const hubFwId = nextId();
  cells.push(cell(hubFwId, "Azure Firewall", STYLES.hubInner, hubX + 15, hubY + 35, 100, 30));
  const hubGwId = nextId();
  cells.push(cell(hubGwId, "ER / VPN Gateway", STYLES.hubInner, hubX + 125, hubY + 35, 100, 30));
  const hubBastId = nextId();
  cells.push(cell(hubBastId, "Azure Bastion", STYLES.hubInner, hubX + 15, hubY + 75, 100, 30));
  const hubMonId = nextId();
  cells.push(cell(hubMonId, "Log Analytics", STYLES.hubInner, hubX + 125, hubY + 75, 100, 30));
  const hubDnsId = nextId();
  cells.push(cell(hubDnsId, "Private DNS", STYLES.hubInner, hubX + 70, hubY + 115, 100, 30));

  // Spoke VNets — one per workload group, alternating left/right columns
  const leftCol = 600;
  const rightCol = 1280;
  const spokeW = 200, spokeH = 70;
  let leftY = 230, rightY = 230;
  const leftSpacing = 90, rightSpacing = 90;

  workloadGroups.forEach((wg, idx) => {
    const onLeft = idx % 2 === 0;
    const x = onLeft ? leftCol : rightCol;
    const y = onLeft ? leftY : rightY;
    if (onLeft) leftY += leftSpacing; else rightY += rightSpacing;

    const sId = nextId();
    cells.push(cell(sId, `Spoke VNet\n${wg}`, STYLES.spokeBox, x, y, spokeW, spokeH));
    cells.push(edge(nextId(), sId, hubId, STYLES.edge, "peer"));
  });

  // ===== DR REGION (optional) =====
  if (drRegion) {
    cells.push(cell("drSection", `Disaster Recovery \u2014 ${drRegion}`, STYLES.sectionTitle, 560, 710, 1000, 30));
    cells.push(cell(nextId(), `DR Region: ${drRegion}`, STYLES.regionFrame, 560, 750, 1000, 220));

    const drHubId = nextId();
    cells.push(cell(drHubId, "Hub VNet (DR)", STYLES.hubBox, hubX, 800, hubW, 100));
    cells.push(cell(nextId(), "Recovery Services Vault", STYLES.hubInner, hubX + 15, 830, 100, 30));
    cells.push(cell(nextId(), "Site Recovery", STYLES.hubInner, hubX + 125, 830, 100, 30));

    const drSpokeId = nextId();
    cells.push(cell(drSpokeId, "Spoke VNets (replica)", STYLES.spokeBox, leftCol, 815, spokeW, 70));
    cells.push(edge(nextId(), drSpokeId, drHubId, STYLES.edge));

    // ASR replication arrow between primary hub and DR hub
    cells.push(edge(nextId(), hubId, drHubId, STYLES.edgeDashed, "ASR / Backup replication"));
  }

  // ===== LEGEND =====
  const legendY = drRegion ? 990 : 720;
  cells.push(cell("legendTitle", "Legend", STYLES.sectionTitle, 40, legendY, 200, 25));
  cells.push(cell(nextId(), "Management Group", STYLES.mgBox, 40, legendY + 30, 160, 26));
  cells.push(cell(nextId(), "Platform", STYLES.mgBoxPlatform, 220, legendY + 30, 160, 26));
  cells.push(cell(nextId(), "Landing Zone", STYLES.mgBoxLz, 400, legendY + 30, 160, 26));
  cells.push(cell(nextId(), "Hub / Spoke", STYLES.hubBox, 580, legendY + 30, 160, 26));
  cells.push(cell(nextId(), "Spoke VNet", STYLES.spokeBox, 760, legendY + 30, 160, 26));
  if (drRegion) cells.push(cell(nextId(), "DR / BCDR", STYLES.drBox, 940, legendY + 30, 160, 26));

  const pageHeight = drRegion ? 1100 : 820;

  // Wrap everything in the standard drawio document shell.
  return `<?xml version="1.0" encoding="UTF-8"?>
<mxfile host="Dr.BOMAgent" agent="DrBOMAgent/1.0" version="22.1.0">
  <diagram name="Landing Zone" id="lz-${customerSlug}">
    <mxGraphModel dx="1600" dy="${pageHeight}" grid="1" gridSize="10" guides="1" tooltips="1" connect="1" arrows="1" fold="1" page="1" pageScale="1" pageWidth="1600" pageHeight="${pageHeight}" math="0" shadow="0">
      <root>
        <mxCell id="0"/>
        <mxCell id="1" parent="0"/>
        ${cells.join("\n        ")}
      </root>
    </mxGraphModel>
  </diagram>
</mxfile>`;
}

module.exports = { buildLandingZoneDiagram };
